### ISSUE TITLE
Folder UIElements missing

### ISSUE THREAD

**Issue by wottpal** [Sirage-t/react-chrome-extension-MV3#1]
Hey @Sirage-t, first I want to say thank you! This is by far the best & most modern extension boilerplate I've found (and there are many!). This repo deserves more attention!

I just noticed I've had to create an `src/UIElements` folder (otherwise the script failed). Maybe you should add it with a `.gitkeep` file into the repo 🤷‍♂️

**Comment by Sirage-t** [comment]
Hi @wottpal , thank you for your comment. It means a lot. I'm glad you find a use of this nearly abandoned project.

I'll check why the folder got deleted and add a `.gitkeep` file like you suggested :).
